### ISSUE TITLE
Swear filter interferes with links

### ISSUE THREAD

**Issue by jjroley** [KestronProgramming/Stewbot#2]
@Kestron06 looking at the current word matching RegEx, it looks like it will match character sets with digits on both sides (why is that?) If that is removed it should resolve the problem with character sets in links that match one of the disallowed words unintentionally (wrapped in digits.)

Separate sanitization can be done for links, but links would need to be matched as a whole. The resulting output could be formatted as [ censored link ]( original link ) taking advantage of markdown or removed entirely from the message to prevent broken links.

**Comment by Kestron06** [comment]
Yeah I can fix it to ignore if numbers are on either side, thanks
